server:
  port: 8080
  servlet:
    context-path: /push

spring:
  datasource:
    
  #logging:
    #  level: DemoApplicationTests = trace
    hikari:
      connection-timeout: 60000
      idle-timeout: 60000
      validation-timeout: 3000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 30
  #    禁用模板缓存
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

#  jpa:
mybatis:
  config-location: classpath:mybaties/mybatis-config.xml
  mapper-locations: classpath:mybaties/mapper/*.xml
#  打印sql
logging:
  level:
    com:
        dao: debug
        controller: debug
  file: ./logs/core.log

#    show-sql: true
message:
  
## 设置单个文件最大内存
#  multipart.maxFileSize=50Mb
#  # 设置所有文件最大内存
#  multipart.maxRequestSize=50Mb
#  # 自定义文件上传路径
#  is_test=true
#  rest_server=open.ucpaas.com
is_test : true
rest_server : true
web:
  upload-path: D:/Develop/Files/Photos/
#  web.upload-path=E:/Develop/Files/Photos/
