server:
  port: 8080
  servlet:
    context-path: /push

spring:
  datasource:
    url: jdbc:mysql://124.95.165.189:3306/ping?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: ping
    password: 1qaz@WSX
    driver-class-name: com.mysql.cj.jdbc.Driver
  #logging:
    #  level: DemoApplicationTests = trace
    hikari:
      connection-timeout: 60000
      idle-timeout: 60000
      validation-timeout: 3000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 30
  #    禁用模板缓存
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

#  jpa:
mybatis:
  config-location: classpath:mybaties/mybatis-config.xml
  mapper-locations: classpath:mybaties/mapper/*.xml
#  打印sql
logging:
  level:
    com:
        dao: debug
        controller: debug
  file: ./logs/core.log

#    show-sql: true
message:
  sid: 48a07b3fec5b348c3d857c070367e47f
  token: 9c950b8f33b61e4d7f1dfc20e4daa3b2
  appid: 076c9f23055843e19a62e13273a77a10
  templateid: 369025
  uid: 4584
## 设置单个文件最大内存
#  multipart.maxFileSize=50Mb
#  # 设置所有文件最大内存
#  multipart.maxRequestSize=50Mb
#  # 自定义文件上传路径
#  is_test=true
#  rest_server=open.ucpaas.com
is_test : true
rest_server : true
web:
  upload-path: D:/Develop/Files/Photos/
#  web.upload-path=E:/Develop/Files/Photos/
